FROM mcr.microsoft.com/dotnet/sdk:7.0
ARG bdd_host
ARG bdd_pwd
ARG keycloak_pwd
ARG uri
COPY . /src/myWebApp
ENV ParkingContextConnectionString= 'Server=mssqlparcindus_cicd;Database=parcIndus;User Id=parcadmin;Password=!@pside2022!;'
ENV KeycloakPasswordUser='pyLcVV$tAFRaNv3J'
ENV WebsiteUri='https://parking.deploy.indus.aix.apsdigit.lan'
RUN echo $bdd_host
RUN echo "$bdd_host"
RUN echo $bdd_pwd
RUN echo "$bdd_pwd"
RUN echo $keycloak_pwd
RUN echo "$keycloak_pwd"
RUN echo $uri
RUN echo "$uri"
RUN mkdir /app
RUN mv /src/myWebApp/GestionPlacesParking/Settings/keycloak.Development.json /src/myWebApp/GestionPlacesParking/Settings/keycloak.Production.json 
RUN dotnet tool install -g dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /src/myWebApp
RUN dotnet restore /src/myWebApp/GestionPlacesParking/GestionPlacesParking.Web.UI.csproj
RUN dotnet build /src/myWebApp/GestionPlacesParking/GestionPlacesParking.Web.UI.csproj -c Release -o /app/
RUN dotnet publish /src/myWebApp/GestionPlacesParking/GestionPlacesParking.Web.UI.csproj -c Release -o /app/
CMD  ["bash","/src/myWebApp/DevOps/builder/migration.sh"]
