FROM mcr.microsoft.com/dotnet/sdk:7.0
ARG parking_connexion
ARG keycloak_pwd
ARG uri
ENV ParkingContextConnectionString=$parking_connexion
ENV KeycloakPasswordUser=$keycloak
ENV WebsiteUri= $uri
COPY . /src/myWebApp
RUN mkdir /app
RUN mv /src/myWebApp/GestionPlacesParking/Settings/keycloak.Development.json /src/myWebApp/GestionPlacesParking/Settings/keycloak.Production.json 
RUN dotnet tool install -g dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /src/myWebApp
RUN dotnet restore /src/myWebApp/GestionPlacesParking/GestionPlacesParking.Web.UI.csproj
RUN dotnet build /src/myWebApp/GestionPlacesParking/GestionPlacesParking.Web.UI.csproj -c Release -o /app/
RUN dotnet publish /src/myWebApp/GestionPlacesParking/GestionPlacesParking.Web.UI.csproj -c Release -o /app/
CMD  ["bash","/src/myWebApp/DevOps/builder/migration.sh"]
