FROM mcr.microsoft.com/dotnet/sdk:7.0
ENV ParkingContextConnectionString='Server=mssql1;Database=parcIndus;User Id=parcadmin;Password=!@pside2022!;'
ENV IsSso=1
ENV WebsiteUri='https://parking.deploy.indus.aix.apsdigit.lan'
WORKDIR /app
CMD  ["dotnet","GestionPlacesParking.Web.UI.dll"]