# Made by Apside - 2023
stages:
  - docker-images
  - deploy

create-image-sql:
  stage: docker-images
  image: docker:20.10.16
  tags:
    - docker
  variables:
    REGISTRY_USER: $HARBGOR_REGISTRY_USER
    REGISTRY_PASSWORD: $HARBOR_REGISTRY_PASSWORD
    REGISTRY_URL: harbor.indus.aix.apsdigit.lan
    DOCKER_IMAGE: harbor.indus.aix.apsdigit.lan/parcindus/mssqlparcindus:$CI_COMMIT_REF_NAME
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD https://$REGISTRY_URL
  script:
    - "docker build -t $DOCKER_IMAGE -f DevOps/mssql/dockerfile ."
    - docker push $DOCKER_IMAGE

create-image-builder:
    stage: docker-images
    image: docker:20.10.16
    tags:
    - docker
    variables:
        REGISTRY_USER: $HARBGOR_REGISTRY_USER
        REGISTRY_PASSWORD: $HARBOR_REGISTRY_PASSWORD
        REGISTRY_URL: harbor.indus.aix.apsdigit.lan
        DOCKER_IMAGE: harbor.indus.aix.apsdigit.lan/parcindus/dotnetbuildparcindus:$CI_COMMIT_REF_NAME
    before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD https://$REGISTRY_URL
    script:
    - "docker build -t $DOCKER_IMAGE -f DevOps/builder/dockerfile ."
    - docker push $DOCKER_IMAGE

deploy-BDD:
  stage: deploy
  image: docker:20.10.16
  tags:
    - docker
  variables:
    REGISTRY_USER: $HARBGOR_REGISTRY_USER
    REGISTRY_PASSWORD: $HARBOR_REGISTRY_PASSWORD
    REGISTRY_URL: harbor.indus.aix.apsdigit.lan
    DOCKER_IMAGE_SQL: harbor.indus.aix.apsdigit.lan/parcindus/mssqlparcindus:$CI_COMMIT_REF_NAME
    DOCKER_CONTAINER_NAME_SQL: mssql:$CI_COMMIT_REF_NAME
    DOCKER_VOLUME: BDDparcindus$CI_COMMIT_REF_NAME
    DOCKER_NETWORK: parcindus
    CI_DEBUG_TRACE: "true"
  # To know how this is working : https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-docker-socket-binding
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD https://$REGISTRY_URL
  script:
    # Stop and remove the container if it exists
    - docker stop $DOCKER_CONTAINER_NAME_SQL  || true
    - docker rm $DOCKER_CONTAINER_NAME_SQL  || true
    - docker network rm $DOCKER_NETWORK || true
    - docker volume rm $DOCKER_VOLUME || true
    # Create the network
    - docker network create $DOCKER_NETWORK || true
    - docker volume create $DOCKER_VOLUME || true
    # First run the back, with little sleep after it to let it some time
    - "docker run -d --rm \
    --env ACCEPT_EULA=$ACCEPT_EULA \
    --env SA_PASSWORD=$SA_PASSWORD \
    --env MSSQL_PID=$MSSQL_PID \
    --mount=$DOCKER_VOLUME:/var/opt/mssql/data \
    --network=$DOCKER_NETWORK \
    --name $DOCKER_CONTAINER_NAME_SQL"
    - sleep 30


    
