services:
  builder:
    image: dotnetbuildparcindus:${VERSION}
    container_name: parcindusbuilder
    volumes:
      - appparcindus:/app
    networks:
      - parcindus
  app:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    environment:
      - ParkingContextConnectionString=Server=mssql1;Database=parcIndus;User Id=parcadmin;Password=!@pside2022!;
      - IsSso=1
      - WebsiteUri=http://localhost
    container_name: parcindusapp
    ports:
      - 8086:80
    networks:
      - parcindus
    volumes:
      - appparcindus:/app
    working_dir: /app
    command: ["dotnet", "GestionPlacesParking.Web.UI.dll"]
    depends_on:
      - builder
networks:
  parcindus:
    external: true
volumes:
  appparcindus: 
    external: true     
