services:
  builder:
    image: harbor.indus.aix.apsdigit.lan/parcindus/dotnetbuildparcindus:${VERSION}
    container_name: parcindusbuilder
    volumes:
      - appparcindus:/app
    networks:
      - parcindus
  app:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    environment:
      - parkingContextConnectionString=Server=mssql1;Database=parcIndus;User Id=parcadmin;Password=!@pside2022!;
      - IsSso=1
      - WebsiteUri=http://parking.indus.aix.apsdigit.lan
    container_name: parcindusapp
    networks:
      - parcindus
    volumes:
      - appparcindus:/app
    working_dir: /app
    command: ["dotnet", "GestionPlacesParking.Web.UI.dll"]
    labels:
      - "traefik.http.services.parking.LoadBalancer.server.port=80"
      - "traefik.http.routers.parking.rule=Host(`parking.indus.aix.apsdigit.lan`)"
      - "traefik.http.routers.parking.entrypoints=http,https"
      - "traefik.http.routers.parking.service=parking"
      - "traefik.http.routers.parking.tls=true"
      - "traefik.http.services.parking.loadbalancer.server.scheme=https"
    expose:
      - 80
      - 443
    depends_on:
      - builder
networks:
  parcindus:
    external: true
volumes:
  appparcindus: 
    external: true    
  
 
