/*
Enter custom T-SQL here that would run after SQL Server has started up. 
*/

CREATE DATABASE [parcIndus]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'parcIndus', FILENAME = N'/var/opt/mssql/data/parcIndus.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'parcIndus_log', FILENAME = N'/var/opt/mssql/data/parcIndus_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [parcIndus] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [parcIndus] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [parcIndus] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [parcIndus] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [parcIndus] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [parcIndus] SET ARITHABORT OFF 
GO
ALTER DATABASE [parcIndus] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [parcIndus] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [parcIndus] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [parcIndus] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [parcIndus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [parcIndus] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [parcIndus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [parcIndus] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [parcIndus] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [parcIndus] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [parcIndus] SET  DISABLE_BROKER 
GO
ALTER DATABASE [parcIndus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [parcIndus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [parcIndus] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [parcIndus] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [parcIndus] SET  READ_WRITE 
GO
ALTER DATABASE [parcIndus] SET RECOVERY FULL 
GO
ALTER DATABASE [parcIndus] SET  MULTI_USER 
GO
ALTER DATABASE [parcIndus] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [parcIndus] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [parcIndus] SET DELAYED_DURABILITY = DISABLED 
GO
USE [parcIndus]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [parcIndus]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [parcIndus] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [parcadmin] WITH PASSWORD=N'!@pside2022!', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [parcadmin]
GO
USE [parcIndus]
GO
CREATE USER [parcadmin] FOR LOGIN [parcadmin]
GO
USE [parcIndus]
GO
ALTER ROLE [db_owner] ADD MEMBER [parcadmin]
GO