FROM mcr.microsoft.com/mssql/server:latest

#Creattion dossier execution
RUN mkdir -p /usr/config
WORKDIR /usr/config

# Copie + permission script BDD APP
COPY --chown=mssql:mssql DevOps/mssql/config/ /usr/config

ENTRYPOINT ["./entrypoint.sh"]
